import type { Metadata } from "next";
import { Raleway, Space_Grotesk } from "next/font/google";
import "../styles/global.css";
import Navbar from "@/components/Navbar";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });
const space = Space_Grotesk({ subsets: ["latin"], variable: "--font-space" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${space.variable} font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
